version: '3'
services:
  learningmachines_client:
    container_name: learningmachines_client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
     - "4200:4200"
    networks:
    - learningmachines_nw
    volumes:
    - ./client:/app
    - /app/node_modules

networks:
  learningmachines_nw:
    driver: bridge
